export default Routes = {
  MAIN: 'MAIN',
  PRODUCTBYCATEGORY: 'PRODUCTBYCATEGORY',
  CARTSUBMIT: 'CARTSUBMIT',
  ADDRESS: 'ADDRESS',
  ADDADDRESS: 'ADDADDRESS',
  MYORDERS: 'MYORDERS',
  SEARCH: 'SEARCH',
  SEARCHRESULT: 'SEARCHRESULT',
  PRODUCTRESULT:'PRODUCTRESULT'
};
